// @generated by protoc-gen-es v2.0.0 with parameter "target=js+dts"
// @generated from file doota/google/v1/google.proto (package doota.google.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file doota/google/v1/google.proto.
 */
export declare const file_doota_google_v1_google: GenFile;

/**
 * @generated from message doota.google.v1.IntegrationResponse
 */
export declare type IntegrationResponse = Message<"doota.google.v1.IntegrationResponse"> & {
  /**
   * @generated from oneof doota.google.v1.IntegrationResponse.result
   */
  result: {
    /**
     * @generated from field: doota.google.v1.Integration integration = 1;
     */
    value: Integration;
    case: "integration";
  } | {
    /**
     * @generated from field: doota.google.v1.IntegrationInvalidRefreshTokenError invalid_refresh_token = 2;
     */
    value: IntegrationInvalidRefreshTokenError;
    case: "invalidRefreshToken";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message doota.google.v1.IntegrationResponse.
 * Use `create(IntegrationResponseSchema)` to create a new message.
 */
export declare const IntegrationResponseSchema: GenMessage<IntegrationResponse>;

/**
 * @generated from message doota.google.v1.Integration
 */
export declare type Integration = Message<"doota.google.v1.Integration"> & {
  /**
   * @generated from field: repeated doota.google.v1.User users = 1;
   */
  users: User[];
};

/**
 * Describes the message doota.google.v1.Integration.
 * Use `create(IntegrationSchema)` to create a new message.
 */
export declare const IntegrationSchema: GenMessage<Integration>;

/**
 * @generated from message doota.google.v1.SetupMailboxWatchRequest
 */
export declare type SetupMailboxWatchRequest = Message<"doota.google.v1.SetupMailboxWatchRequest"> & {
  /**
   * @generated from field: string code = 2;
   */
  code: string;
};

/**
 * Describes the message doota.google.v1.SetupMailboxWatchRequest.
 * Use `create(SetupMailboxWatchRequestSchema)` to create a new message.
 */
export declare const SetupMailboxWatchRequestSchema: GenMessage<SetupMailboxWatchRequest>;

/**
 * @generated from message doota.google.v1.RenewMessageSourceRequest
 */
export declare type RenewMessageSourceRequest = Message<"doota.google.v1.RenewMessageSourceRequest"> & {
  /**
   * @generated from field: string message_source_id = 1;
   */
  messageSourceId: string;
};

/**
 * Describes the message doota.google.v1.RenewMessageSourceRequest.
 * Use `create(RenewMessageSourceRequestSchema)` to create a new message.
 */
export declare const RenewMessageSourceRequestSchema: GenMessage<RenewMessageSourceRequest>;

/**
 * @generated from message doota.google.v1.SetupMailboxWatchResponse
 */
export declare type SetupMailboxWatchResponse = Message<"doota.google.v1.SetupMailboxWatchResponse"> & {
  /**
   * @generated from field: string refresh_token = 1;
   */
  refreshToken: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * @generated from field: uint64 history_id = 3;
   */
  historyId: bigint;

  /**
   * @generated from field: int64 expiration = 4;
   */
  expiration: bigint;
};

/**
 * Describes the message doota.google.v1.SetupMailboxWatchResponse.
 * Use `create(SetupMailboxWatchResponseSchema)` to create a new message.
 */
export declare const SetupMailboxWatchResponseSchema: GenMessage<SetupMailboxWatchResponse>;

/**
 * @generated from message doota.google.v1.SetupWorkspaceAdminRequest
 */
export declare type SetupWorkspaceAdminRequest = Message<"doota.google.v1.SetupWorkspaceAdminRequest"> & {
  /**
   * @generated from field: string code = 1;
   */
  code: string;
};

/**
 * Describes the message doota.google.v1.SetupWorkspaceAdminRequest.
 * Use `create(SetupWorkspaceAdminRequestSchema)` to create a new message.
 */
export declare const SetupWorkspaceAdminRequestSchema: GenMessage<SetupWorkspaceAdminRequest>;

/**
 * @generated from message doota.google.v1.SetupWorkspaceAdminResponse
 */
export declare type SetupWorkspaceAdminResponse = Message<"doota.google.v1.SetupWorkspaceAdminResponse"> & {
  /**
   * @generated from field: string refresh_token = 1;
   */
  refreshToken: string;
};

/**
 * Describes the message doota.google.v1.SetupWorkspaceAdminResponse.
 * Use `create(SetupWorkspaceAdminResponseSchema)` to create a new message.
 */
export declare const SetupWorkspaceAdminResponseSchema: GenMessage<SetupWorkspaceAdminResponse>;

/**
 * @generated from message doota.google.v1.User
 */
export declare type User = Message<"doota.google.v1.User"> & {
  /**
   * google user's id
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * google user's email
   *
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * google user's name
   *
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * freighstream system user id
   *
   * @generated from field: optional string user_id = 4;
   */
  userId?: string;

  /**
   * freighstream system message source id ID
   *
   * @generated from field: optional string message_source_id = 5;
   */
  messageSourceId?: string;

  /**
   * @generated from field: bool active_watch = 6;
   */
  activeWatch: boolean;
};

/**
 * Describes the message doota.google.v1.User.
 * Use `create(UserSchema)` to create a new message.
 */
export declare const UserSchema: GenMessage<User>;

/**
 * @generated from message doota.google.v1.GetIntegrationRequest
 */
export declare type GetIntegrationRequest = Message<"doota.google.v1.GetIntegrationRequest"> & {
  /**
   * @generated from field: string integration_id = 1;
   */
  integrationId: string;
};

/**
 * Describes the message doota.google.v1.GetIntegrationRequest.
 * Use `create(GetIntegrationRequestSchema)` to create a new message.
 */
export declare const GetIntegrationRequestSchema: GenMessage<GetIntegrationRequest>;

/**
 * @generated from message doota.google.v1.IntegrationInvalidRefreshTokenError
 */
export declare type IntegrationInvalidRefreshTokenError = Message<"doota.google.v1.IntegrationInvalidRefreshTokenError"> & {
  /**
   * @generated from field: string cause = 1;
   */
  cause: string;
};

/**
 * Describes the message doota.google.v1.IntegrationInvalidRefreshTokenError.
 * Use `create(IntegrationInvalidRefreshTokenErrorSchema)` to create a new message.
 */
export declare const IntegrationInvalidRefreshTokenErrorSchema: GenMessage<IntegrationInvalidRefreshTokenError>;

/**
 * @generated from service doota.google.v1.GoogleService
 */
export declare const GoogleService: GenService<{
  /**
   * this should be called when the user consents when he logs in
   *
   * @generated from rpc doota.google.v1.GoogleService.SetupMailboxWatch
   */
  setupMailboxWatch: {
    methodKind: "unary";
    input: typeof SetupMailboxWatchRequestSchema;
    output: typeof SetupMailboxWatchResponseSchema;
  },
  /**
   * @generated from rpc doota.google.v1.GoogleService.GetIntegration
   */
  getIntegration: {
    methodKind: "unary";
    input: typeof GetIntegrationRequestSchema;
    output: typeof IntegrationResponseSchema;
  },
  /**
   * this should be called when the admin initially connect to their google
   * workspace, it will return a refresh token
   *
   * @generated from rpc doota.google.v1.GoogleService.SetupWorkspaceAdmin
   */
  setupWorkspaceAdmin: {
    methodKind: "unary";
    input: typeof SetupWorkspaceAdminRequestSchema;
    output: typeof SetupWorkspaceAdminResponseSchema;
  },
}>;

