// @generated by protoc-gen-es v2.0.0 with parameter "target=js+dts"
// @generated from file doota/google/v1/google.proto (package doota.google.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file doota/google/v1/google.proto.
 */
export const file_doota_google_v1_google = /*@__PURE__*/
  fileDesc("Chxkb290YS9nb29nbGUvdjEvZ29vZ2xlLnByb3RvEg9kb290YS5nb29nbGUudjEiqwEKE0ludGVncmF0aW9uUmVzcG9uc2USMwoLaW50ZWdyYXRpb24YASABKAsyHC5kb290YS5nb29nbGUudjEuSW50ZWdyYXRpb25IABJVChVpbnZhbGlkX3JlZnJlc2hfdG9rZW4YAiABKAsyNC5kb290YS5nb29nbGUudjEuSW50ZWdyYXRpb25JbnZhbGlkUmVmcmVzaFRva2VuRXJyb3JIAEIICgZyZXN1bHQiMwoLSW50ZWdyYXRpb24SJAoFdXNlcnMYASADKAsyFS5kb290YS5nb29nbGUudjEuVXNlciIoChhTZXR1cE1haWxib3hXYXRjaFJlcXVlc3QSDAoEY29kZRgCIAEoCSI2ChlSZW5ld01lc3NhZ2VTb3VyY2VSZXF1ZXN0EhkKEW1lc3NhZ2Vfc291cmNlX2lkGAEgASgJImkKGVNldHVwTWFpbGJveFdhdGNoUmVzcG9uc2USFQoNcmVmcmVzaF90b2tlbhgBIAEoCRINCgVlbWFpbBgCIAEoCRISCgpoaXN0b3J5X2lkGAMgASgEEhIKCmV4cGlyYXRpb24YBCABKAMiKgoaU2V0dXBXb3Jrc3BhY2VBZG1pblJlcXVlc3QSDAoEY29kZRgBIAEoCSI0ChtTZXR1cFdvcmtzcGFjZUFkbWluUmVzcG9uc2USFQoNcmVmcmVzaF90b2tlbhgBIAEoCSKdAQoEVXNlchIKCgJpZBgBIAEoCRINCgVlbWFpbBgCIAEoCRIMCgRuYW1lGAMgASgJEhQKB3VzZXJfaWQYBCABKAlIAIgBARIeChFtZXNzYWdlX3NvdXJjZV9pZBgFIAEoCUgBiAEBEhQKDGFjdGl2ZV93YXRjaBgGIAEoCEIKCghfdXNlcl9pZEIUChJfbWVzc2FnZV9zb3VyY2VfaWQiLwoVR2V0SW50ZWdyYXRpb25SZXF1ZXN0EhYKDmludGVncmF0aW9uX2lkGAEgASgJIjQKI0ludGVncmF0aW9uSW52YWxpZFJlZnJlc2hUb2tlbkVycm9yEg0KBWNhdXNlGAEgASgJMs0CCg1Hb29nbGVTZXJ2aWNlEmoKEVNldHVwTWFpbGJveFdhdGNoEikuZG9vdGEuZ29vZ2xlLnYxLlNldHVwTWFpbGJveFdhdGNoUmVxdWVzdBoqLmRvb3RhLmdvb2dsZS52MS5TZXR1cE1haWxib3hXYXRjaFJlc3BvbnNlEl4KDkdldEludGVncmF0aW9uEiYuZG9vdGEuZ29vZ2xlLnYxLkdldEludGVncmF0aW9uUmVxdWVzdBokLmRvb3RhLmdvb2dsZS52MS5JbnRlZ3JhdGlvblJlc3BvbnNlEnAKE1NldHVwV29ya3NwYWNlQWRtaW4SKy5kb290YS5nb29nbGUudjEuU2V0dXBXb3Jrc3BhY2VBZG1pblJlcXVlc3QaLC5kb290YS5nb29nbGUudjEuU2V0dXBXb3Jrc3BhY2VBZG1pblJlc3BvbnNlQjdaNWdpdGh1Yi5jb20vc2hhbmszMTgvZG9vdGEvcGIvZG9vdGEvZ29vZ2xlL3YxO3BiZ29vZ2xlYgZwcm90bzM");

/**
 * Describes the message doota.google.v1.IntegrationResponse.
 * Use `create(IntegrationResponseSchema)` to create a new message.
 */
export const IntegrationResponseSchema = /*@__PURE__*/
  messageDesc(file_doota_google_v1_google, 0);

/**
 * Describes the message doota.google.v1.Integration.
 * Use `create(IntegrationSchema)` to create a new message.
 */
export const IntegrationSchema = /*@__PURE__*/
  messageDesc(file_doota_google_v1_google, 1);

/**
 * Describes the message doota.google.v1.SetupMailboxWatchRequest.
 * Use `create(SetupMailboxWatchRequestSchema)` to create a new message.
 */
export const SetupMailboxWatchRequestSchema = /*@__PURE__*/
  messageDesc(file_doota_google_v1_google, 2);

/**
 * Describes the message doota.google.v1.RenewMessageSourceRequest.
 * Use `create(RenewMessageSourceRequestSchema)` to create a new message.
 */
export const RenewMessageSourceRequestSchema = /*@__PURE__*/
  messageDesc(file_doota_google_v1_google, 3);

/**
 * Describes the message doota.google.v1.SetupMailboxWatchResponse.
 * Use `create(SetupMailboxWatchResponseSchema)` to create a new message.
 */
export const SetupMailboxWatchResponseSchema = /*@__PURE__*/
  messageDesc(file_doota_google_v1_google, 4);

/**
 * Describes the message doota.google.v1.SetupWorkspaceAdminRequest.
 * Use `create(SetupWorkspaceAdminRequestSchema)` to create a new message.
 */
export const SetupWorkspaceAdminRequestSchema = /*@__PURE__*/
  messageDesc(file_doota_google_v1_google, 5);

/**
 * Describes the message doota.google.v1.SetupWorkspaceAdminResponse.
 * Use `create(SetupWorkspaceAdminResponseSchema)` to create a new message.
 */
export const SetupWorkspaceAdminResponseSchema = /*@__PURE__*/
  messageDesc(file_doota_google_v1_google, 6);

/**
 * Describes the message doota.google.v1.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema = /*@__PURE__*/
  messageDesc(file_doota_google_v1_google, 7);

/**
 * Describes the message doota.google.v1.GetIntegrationRequest.
 * Use `create(GetIntegrationRequestSchema)` to create a new message.
 */
export const GetIntegrationRequestSchema = /*@__PURE__*/
  messageDesc(file_doota_google_v1_google, 8);

/**
 * Describes the message doota.google.v1.IntegrationInvalidRefreshTokenError.
 * Use `create(IntegrationInvalidRefreshTokenErrorSchema)` to create a new message.
 */
export const IntegrationInvalidRefreshTokenErrorSchema = /*@__PURE__*/
  messageDesc(file_doota_google_v1_google, 9);

/**
 * @generated from service doota.google.v1.GoogleService
 */
export const GoogleService = /*@__PURE__*/
  serviceDesc(file_doota_google_v1_google, 0);

