// @generated by protoc-gen-es v2.0.0 with parameter "target=js+dts"
// @generated from file doota/reddit/v1/reddit.proto (package doota.reddit.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file doota/reddit/v1/reddit.proto.
 */
export declare const file_doota_reddit_v1_reddit: GenFile;

/**
 * @generated from message doota.reddit.v1.Integration
 */
export declare type Integration = Message<"doota.reddit.v1.Integration"> & {
  /**
   * @generated from field: string user_name = 1;
   */
  userName: string;
};

/**
 * Describes the message doota.reddit.v1.Integration.
 * Use `create(IntegrationSchema)` to create a new message.
 */
export declare const IntegrationSchema: GenMessage<Integration>;

