// @generated by protoc-gen-es v2.0.0 with parameter "target=js+dts"
// @generated from file doota/reddit/v1/reddit.proto (package doota.reddit.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file doota/reddit/v1/reddit.proto.
 */
export declare const file_doota_reddit_v1_reddit: GenFile;

/**
 * @generated from message doota.reddit.v1.Integration
 */
export declare type Integration = Message<"doota.reddit.v1.Integration"> & {
  /**
   * @generated from field: string user_name = 1;
   */
  userName: string;
};

/**
 * Describes the message doota.reddit.v1.Integration.
 * Use `create(IntegrationSchema)` to create a new message.
 */
export declare const IntegrationSchema: GenMessage<Integration>;

/**
 * @generated from message doota.reddit.v1.RemoveSubRedditRequest
 */
export declare type RemoveSubRedditRequest = Message<"doota.reddit.v1.RemoveSubRedditRequest"> & {
  /**
   * eg. r/SAAS
   *
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message doota.reddit.v1.RemoveSubRedditRequest.
 * Use `create(RemoveSubRedditRequestSchema)` to create a new message.
 */
export declare const RemoveSubRedditRequestSchema: GenMessage<RemoveSubRedditRequest>;

/**
 * @generated from message doota.reddit.v1.AddSubRedditRequest
 */
export declare type AddSubRedditRequest = Message<"doota.reddit.v1.AddSubRedditRequest"> & {
  /**
   * eg. r/SAAS
   *
   * @generated from field: string url = 1;
   */
  url: string;
};

/**
 * Describes the message doota.reddit.v1.AddSubRedditRequest.
 * Use `create(AddSubRedditRequestSchema)` to create a new message.
 */
export declare const AddSubRedditRequestSchema: GenMessage<AddSubRedditRequest>;

/**
 * @generated from message doota.reddit.v1.SubReddit
 */
export declare type SubReddit = Message<"doota.reddit.v1.SubReddit"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string url = 2;
   */
  url: string;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from field: string description = 4;
   */
  description: string;

  /**
   * @generated from field: doota.reddit.v1.SubRedditMetadata metadata = 5;
   */
  metadata?: SubRedditMetadata;

  /**
   * @generated from field: optional string title = 6;
   */
  title?: string;
};

/**
 * Describes the message doota.reddit.v1.SubReddit.
 * Use `create(SubRedditSchema)` to create a new message.
 */
export declare const SubRedditSchema: GenMessage<SubReddit>;

/**
 * @generated from message doota.reddit.v1.SubRedditMetadata
 */
export declare type SubRedditMetadata = Message<"doota.reddit.v1.SubRedditMetadata"> & {
};

/**
 * Describes the message doota.reddit.v1.SubRedditMetadata.
 * Use `create(SubRedditMetadataSchema)` to create a new message.
 */
export declare const SubRedditMetadataSchema: GenMessage<SubRedditMetadata>;

/**
 * @generated from message doota.reddit.v1.GetSubredditsResponse
 */
export declare type GetSubredditsResponse = Message<"doota.reddit.v1.GetSubredditsResponse"> & {
  /**
   * @generated from field: repeated doota.reddit.v1.SubReddit subreddits = 1;
   */
  subreddits: SubReddit[];
};

/**
 * Describes the message doota.reddit.v1.GetSubredditsResponse.
 * Use `create(GetSubredditsResponseSchema)` to create a new message.
 */
export declare const GetSubredditsResponseSchema: GenMessage<GetSubredditsResponse>;

