// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: doota/google/v1/google.proto

package pbgoogle

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IntegrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//
	//	*IntegrationResponse_Integration
	//	*IntegrationResponse_InvalidRefreshToken
	Result isIntegrationResponse_Result `protobuf_oneof:"result"`
}

func (x *IntegrationResponse) Reset() {
	*x = IntegrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doota_google_v1_google_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntegrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrationResponse) ProtoMessage() {}

func (x *IntegrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_doota_google_v1_google_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrationResponse.ProtoReflect.Descriptor instead.
func (*IntegrationResponse) Descriptor() ([]byte, []int) {
	return file_doota_google_v1_google_proto_rawDescGZIP(), []int{0}
}

func (m *IntegrationResponse) GetResult() isIntegrationResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *IntegrationResponse) GetIntegration() *Integration {
	if x, ok := x.GetResult().(*IntegrationResponse_Integration); ok {
		return x.Integration
	}
	return nil
}

func (x *IntegrationResponse) GetInvalidRefreshToken() *IntegrationInvalidRefreshTokenError {
	if x, ok := x.GetResult().(*IntegrationResponse_InvalidRefreshToken); ok {
		return x.InvalidRefreshToken
	}
	return nil
}

type isIntegrationResponse_Result interface {
	isIntegrationResponse_Result()
}

type IntegrationResponse_Integration struct {
	Integration *Integration `protobuf:"bytes,1,opt,name=integration,proto3,oneof"`
}

type IntegrationResponse_InvalidRefreshToken struct {
	InvalidRefreshToken *IntegrationInvalidRefreshTokenError `protobuf:"bytes,2,opt,name=invalid_refresh_token,json=invalidRefreshToken,proto3,oneof"`
}

func (*IntegrationResponse_Integration) isIntegrationResponse_Result() {}

func (*IntegrationResponse_InvalidRefreshToken) isIntegrationResponse_Result() {}

type Integration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users []*User `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *Integration) Reset() {
	*x = Integration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doota_google_v1_google_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Integration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Integration) ProtoMessage() {}

func (x *Integration) ProtoReflect() protoreflect.Message {
	mi := &file_doota_google_v1_google_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Integration.ProtoReflect.Descriptor instead.
func (*Integration) Descriptor() ([]byte, []int) {
	return file_doota_google_v1_google_proto_rawDescGZIP(), []int{1}
}

func (x *Integration) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type SetupMailboxWatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *SetupMailboxWatchRequest) Reset() {
	*x = SetupMailboxWatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doota_google_v1_google_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetupMailboxWatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupMailboxWatchRequest) ProtoMessage() {}

func (x *SetupMailboxWatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_doota_google_v1_google_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupMailboxWatchRequest.ProtoReflect.Descriptor instead.
func (*SetupMailboxWatchRequest) Descriptor() ([]byte, []int) {
	return file_doota_google_v1_google_proto_rawDescGZIP(), []int{2}
}

func (x *SetupMailboxWatchRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type RenewMessageSourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageSourceId string `protobuf:"bytes,1,opt,name=message_source_id,json=messageSourceId,proto3" json:"message_source_id,omitempty"`
}

func (x *RenewMessageSourceRequest) Reset() {
	*x = RenewMessageSourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doota_google_v1_google_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenewMessageSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewMessageSourceRequest) ProtoMessage() {}

func (x *RenewMessageSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_doota_google_v1_google_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewMessageSourceRequest.ProtoReflect.Descriptor instead.
func (*RenewMessageSourceRequest) Descriptor() ([]byte, []int) {
	return file_doota_google_v1_google_proto_rawDescGZIP(), []int{3}
}

func (x *RenewMessageSourceRequest) GetMessageSourceId() string {
	if x != nil {
		return x.MessageSourceId
	}
	return ""
}

type SetupMailboxWatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RefreshToken string `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Email        string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	HistoryId    uint64 `protobuf:"varint,3,opt,name=history_id,json=historyId,proto3" json:"history_id,omitempty"`
	Expiration   int64  `protobuf:"varint,4,opt,name=expiration,proto3" json:"expiration,omitempty"`
}

func (x *SetupMailboxWatchResponse) Reset() {
	*x = SetupMailboxWatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doota_google_v1_google_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetupMailboxWatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupMailboxWatchResponse) ProtoMessage() {}

func (x *SetupMailboxWatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_doota_google_v1_google_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupMailboxWatchResponse.ProtoReflect.Descriptor instead.
func (*SetupMailboxWatchResponse) Descriptor() ([]byte, []int) {
	return file_doota_google_v1_google_proto_rawDescGZIP(), []int{4}
}

func (x *SetupMailboxWatchResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *SetupMailboxWatchResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SetupMailboxWatchResponse) GetHistoryId() uint64 {
	if x != nil {
		return x.HistoryId
	}
	return 0
}

func (x *SetupMailboxWatchResponse) GetExpiration() int64 {
	if x != nil {
		return x.Expiration
	}
	return 0
}

type SetupWorkspaceAdminRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *SetupWorkspaceAdminRequest) Reset() {
	*x = SetupWorkspaceAdminRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doota_google_v1_google_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetupWorkspaceAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupWorkspaceAdminRequest) ProtoMessage() {}

func (x *SetupWorkspaceAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_doota_google_v1_google_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupWorkspaceAdminRequest.ProtoReflect.Descriptor instead.
func (*SetupWorkspaceAdminRequest) Descriptor() ([]byte, []int) {
	return file_doota_google_v1_google_proto_rawDescGZIP(), []int{5}
}

func (x *SetupWorkspaceAdminRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type SetupWorkspaceAdminResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RefreshToken string `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
}

func (x *SetupWorkspaceAdminResponse) Reset() {
	*x = SetupWorkspaceAdminResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doota_google_v1_google_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetupWorkspaceAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupWorkspaceAdminResponse) ProtoMessage() {}

func (x *SetupWorkspaceAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_doota_google_v1_google_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupWorkspaceAdminResponse.ProtoReflect.Descriptor instead.
func (*SetupWorkspaceAdminResponse) Descriptor() ([]byte, []int) {
	return file_doota_google_v1_google_proto_rawDescGZIP(), []int{6}
}

func (x *SetupWorkspaceAdminResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// google user's id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// google user's email
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// google user's name
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// freighstream system user id
	UserId *string `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	// freighstream system message source id ID
	MessageSourceId *string `protobuf:"bytes,5,opt,name=message_source_id,json=messageSourceId,proto3,oneof" json:"message_source_id,omitempty"`
	ActiveWatch     bool    `protobuf:"varint,6,opt,name=active_watch,json=activeWatch,proto3" json:"active_watch,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doota_google_v1_google_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_doota_google_v1_google_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_doota_google_v1_google_proto_rawDescGZIP(), []int{7}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *User) GetMessageSourceId() string {
	if x != nil && x.MessageSourceId != nil {
		return *x.MessageSourceId
	}
	return ""
}

func (x *User) GetActiveWatch() bool {
	if x != nil {
		return x.ActiveWatch
	}
	return false
}

type GetIntegrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IntegrationId string `protobuf:"bytes,1,opt,name=integration_id,json=integrationId,proto3" json:"integration_id,omitempty"`
}

func (x *GetIntegrationRequest) Reset() {
	*x = GetIntegrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doota_google_v1_google_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIntegrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIntegrationRequest) ProtoMessage() {}

func (x *GetIntegrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_doota_google_v1_google_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIntegrationRequest.ProtoReflect.Descriptor instead.
func (*GetIntegrationRequest) Descriptor() ([]byte, []int) {
	return file_doota_google_v1_google_proto_rawDescGZIP(), []int{8}
}

func (x *GetIntegrationRequest) GetIntegrationId() string {
	if x != nil {
		return x.IntegrationId
	}
	return ""
}

type IntegrationInvalidRefreshTokenError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cause string `protobuf:"bytes,1,opt,name=cause,proto3" json:"cause,omitempty"`
}

func (x *IntegrationInvalidRefreshTokenError) Reset() {
	*x = IntegrationInvalidRefreshTokenError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doota_google_v1_google_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntegrationInvalidRefreshTokenError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrationInvalidRefreshTokenError) ProtoMessage() {}

func (x *IntegrationInvalidRefreshTokenError) ProtoReflect() protoreflect.Message {
	mi := &file_doota_google_v1_google_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrationInvalidRefreshTokenError.ProtoReflect.Descriptor instead.
func (*IntegrationInvalidRefreshTokenError) Descriptor() ([]byte, []int) {
	return file_doota_google_v1_google_proto_rawDescGZIP(), []int{9}
}

func (x *IntegrationInvalidRefreshTokenError) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

var File_doota_google_v1_google_proto protoreflect.FileDescriptor

var file_doota_google_v1_google_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x64, 0x6f, 0x6f, 0x74, 0x61, 0x2f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x76,
	0x31, 0x2f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f,
	0x64, 0x6f, 0x6f, 0x74, 0x61, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x22,
	0xcd, 0x01, 0x0a, 0x13, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x67,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x64,
	0x6f, 0x6f, 0x74, 0x61, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x49,
	0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0b, 0x69, 0x6e,
	0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x6a, 0x0a, 0x15, 0x69, 0x6e, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x5f, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x5f, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x64, 0x6f, 0x6f, 0x74, 0x61,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x67,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x52, 0x65, 0x66,
	0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00,
	0x52, 0x13, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22,
	0x3a, 0x0a, 0x0b, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2b,
	0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x64, 0x6f, 0x6f, 0x74, 0x61, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x22, 0x2e, 0x0a, 0x18, 0x53,
	0x65, 0x74, 0x75, 0x70, 0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x57, 0x61, 0x74, 0x63, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x47, 0x0a, 0x19, 0x52,
	0x65, 0x6e, 0x65, 0x77, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x5f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x49, 0x64, 0x22, 0x95, 0x01, 0x0a, 0x19, 0x53, 0x65, 0x74, 0x75, 0x70, 0x4d, 0x61,
	0x69, 0x6c, 0x62, 0x6f, 0x78, 0x57, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x5f, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x66, 0x72, 0x65,
	0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1d, 0x0a,
	0x0a, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x09, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x30, 0x0a, 0x1a,
	0x53, 0x65, 0x74, 0x75, 0x70, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x42,
	0x0a, 0x1b, 0x53, 0x65, 0x74, 0x75, 0x70, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a,
	0x0d, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x22, 0xd4, 0x01, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x88, 0x01, 0x01, 0x12, 0x2f, 0x0a, 0x11, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01,
	0x52, 0x0f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49,
	0x64, 0x88, 0x01, 0x01, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x77,
	0x61, 0x74, 0x63, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x61, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x57, 0x61, 0x74, 0x63, 0x68, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x42, 0x14, 0x0a, 0x12, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x22, 0x3e, 0x0a, 0x15, 0x47, 0x65, 0x74,
	0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x6e, 0x74, 0x65,
	0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x3b, 0x0a, 0x23, 0x49, 0x6e, 0x74,
	0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x52,
	0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x61, 0x75, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x63, 0x61, 0x75, 0x73, 0x65, 0x32, 0xcd, 0x02, 0x0a, 0x0d, 0x47, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6a, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x75,
	0x70, 0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x57, 0x61, 0x74, 0x63, 0x68, 0x12, 0x29, 0x2e,
	0x64, 0x6f, 0x6f, 0x74, 0x61, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x65, 0x74, 0x75, 0x70, 0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x57, 0x61, 0x74, 0x63,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x64, 0x6f, 0x6f, 0x74, 0x61,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x75, 0x70,
	0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x57, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5e, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x67,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x2e, 0x64, 0x6f, 0x6f, 0x74, 0x61, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x65,
	0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24,
	0x2e, 0x64, 0x6f, 0x6f, 0x74, 0x61, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x70, 0x0a, 0x13, 0x53, 0x65, 0x74, 0x75, 0x70, 0x57, 0x6f, 0x72,
	0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x2b, 0x2e, 0x64, 0x6f,
	0x6f, 0x74, 0x61, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65,
	0x74, 0x75, 0x70, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x64, 0x6f, 0x6f, 0x74, 0x61,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x75, 0x70,
	0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x68, 0x61, 0x6e, 0x6b, 0x33, 0x31, 0x38, 0x2f, 0x64, 0x6f,
	0x6f, 0x74, 0x61, 0x2f, 0x70, 0x62, 0x2f, 0x64, 0x6f, 0x6f, 0x74, 0x61, 0x2f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x62, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_doota_google_v1_google_proto_rawDescOnce sync.Once
	file_doota_google_v1_google_proto_rawDescData = file_doota_google_v1_google_proto_rawDesc
)

func file_doota_google_v1_google_proto_rawDescGZIP() []byte {
	file_doota_google_v1_google_proto_rawDescOnce.Do(func() {
		file_doota_google_v1_google_proto_rawDescData = protoimpl.X.CompressGZIP(file_doota_google_v1_google_proto_rawDescData)
	})
	return file_doota_google_v1_google_proto_rawDescData
}

var file_doota_google_v1_google_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_doota_google_v1_google_proto_goTypes = []interface{}{
	(*IntegrationResponse)(nil),                 // 0: doota.google.v1.IntegrationResponse
	(*Integration)(nil),                         // 1: doota.google.v1.Integration
	(*SetupMailboxWatchRequest)(nil),            // 2: doota.google.v1.SetupMailboxWatchRequest
	(*RenewMessageSourceRequest)(nil),           // 3: doota.google.v1.RenewMessageSourceRequest
	(*SetupMailboxWatchResponse)(nil),           // 4: doota.google.v1.SetupMailboxWatchResponse
	(*SetupWorkspaceAdminRequest)(nil),          // 5: doota.google.v1.SetupWorkspaceAdminRequest
	(*SetupWorkspaceAdminResponse)(nil),         // 6: doota.google.v1.SetupWorkspaceAdminResponse
	(*User)(nil),                                // 7: doota.google.v1.User
	(*GetIntegrationRequest)(nil),               // 8: doota.google.v1.GetIntegrationRequest
	(*IntegrationInvalidRefreshTokenError)(nil), // 9: doota.google.v1.IntegrationInvalidRefreshTokenError
}
var file_doota_google_v1_google_proto_depIdxs = []int32{
	1, // 0: doota.google.v1.IntegrationResponse.integration:type_name -> doota.google.v1.Integration
	9, // 1: doota.google.v1.IntegrationResponse.invalid_refresh_token:type_name -> doota.google.v1.IntegrationInvalidRefreshTokenError
	7, // 2: doota.google.v1.Integration.users:type_name -> doota.google.v1.User
	2, // 3: doota.google.v1.GoogleService.SetupMailboxWatch:input_type -> doota.google.v1.SetupMailboxWatchRequest
	8, // 4: doota.google.v1.GoogleService.GetIntegration:input_type -> doota.google.v1.GetIntegrationRequest
	5, // 5: doota.google.v1.GoogleService.SetupWorkspaceAdmin:input_type -> doota.google.v1.SetupWorkspaceAdminRequest
	4, // 6: doota.google.v1.GoogleService.SetupMailboxWatch:output_type -> doota.google.v1.SetupMailboxWatchResponse
	0, // 7: doota.google.v1.GoogleService.GetIntegration:output_type -> doota.google.v1.IntegrationResponse
	6, // 8: doota.google.v1.GoogleService.SetupWorkspaceAdmin:output_type -> doota.google.v1.SetupWorkspaceAdminResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_doota_google_v1_google_proto_init() }
func file_doota_google_v1_google_proto_init() {
	if File_doota_google_v1_google_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_doota_google_v1_google_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IntegrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doota_google_v1_google_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Integration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doota_google_v1_google_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetupMailboxWatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doota_google_v1_google_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenewMessageSourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doota_google_v1_google_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetupMailboxWatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doota_google_v1_google_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetupWorkspaceAdminRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doota_google_v1_google_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetupWorkspaceAdminResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doota_google_v1_google_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doota_google_v1_google_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIntegrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doota_google_v1_google_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IntegrationInvalidRefreshTokenError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_doota_google_v1_google_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*IntegrationResponse_Integration)(nil),
		(*IntegrationResponse_InvalidRefreshToken)(nil),
	}
	file_doota_google_v1_google_proto_msgTypes[7].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_doota_google_v1_google_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_doota_google_v1_google_proto_goTypes,
		DependencyIndexes: file_doota_google_v1_google_proto_depIdxs,
		MessageInfos:      file_doota_google_v1_google_proto_msgTypes,
	}.Build()
	File_doota_google_v1_google_proto = out.File
	file_doota_google_v1_google_proto_rawDesc = nil
	file_doota_google_v1_google_proto_goTypes = nil
	file_doota_google_v1_google_proto_depIdxs = nil
}
