// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package models

import (
	"errors"
	"fmt"
)

const (
	// IntegrationStateACTIVE is a IntegrationState of type ACTIVE.
	IntegrationStateACTIVE IntegrationState = "ACTIVE"
	// IntegrationStateAUTHREVOKED is a IntegrationState of type AUTH_REVOKED.
	IntegrationStateAUTHREVOKED IntegrationState = "AUTH_REVOKED"
	// IntegrationStateACCOUNTSUSPENDED is a IntegrationState of type ACCOUNT_SUSPENDED.
	IntegrationStateACCOUNTSUSPENDED IntegrationState = "ACCOUNT_SUSPENDED"
	// IntegrationStateAUTHEXPIRED is a IntegrationState of type AUTH_EXPIRED.
	IntegrationStateAUTHEXPIRED IntegrationState = "AUTH_EXPIRED"
	// IntegrationStateNOTESTABLISHED is a IntegrationState of type NOT_ESTABLISHED.
	IntegrationStateNOTESTABLISHED IntegrationState = "NOT_ESTABLISHED"
)

var ErrInvalidIntegrationState = errors.New("not a valid IntegrationState")

// String implements the Stringer interface.
func (x IntegrationState) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x IntegrationState) IsValid() bool {
	_, err := ParseIntegrationState(string(x))
	return err == nil
}

var _IntegrationStateValue = map[string]IntegrationState{
	"ACTIVE":            IntegrationStateACTIVE,
	"AUTH_REVOKED":      IntegrationStateAUTHREVOKED,
	"ACCOUNT_SUSPENDED": IntegrationStateACCOUNTSUSPENDED,
	"AUTH_EXPIRED":      IntegrationStateAUTHEXPIRED,
	"NOT_ESTABLISHED":   IntegrationStateNOTESTABLISHED,
}

// ParseIntegrationState attempts to convert a string to a IntegrationState.
func ParseIntegrationState(name string) (IntegrationState, error) {
	if x, ok := _IntegrationStateValue[name]; ok {
		return x, nil
	}
	return IntegrationState(""), fmt.Errorf("%s is %w", name, ErrInvalidIntegrationState)
}

const (
	// IntegrationTypeVOICEMILLIS is a IntegrationType of type VOICE_MILLIS.
	IntegrationTypeVOICEMILLIS IntegrationType = "VOICE_MILLIS"
	// IntegrationTypeVOICEVAPI is a IntegrationType of type VOICE_VAPI.
	IntegrationTypeVOICEVAPI IntegrationType = "VOICE_VAPI"
	// IntegrationTypeREDDIT is a IntegrationType of type REDDIT.
	IntegrationTypeREDDIT IntegrationType = "REDDIT"
	// IntegrationTypeSLACKWEBHOOK is a IntegrationType of type SLACK_WEBHOOK.
	IntegrationTypeSLACKWEBHOOK IntegrationType = "SLACK_WEBHOOK"
	// IntegrationTypeREDDITDMLOGIN is a IntegrationType of type REDDIT_DM_LOGIN.
	IntegrationTypeREDDITDMLOGIN IntegrationType = "REDDIT_DM_LOGIN"
)

var ErrInvalidIntegrationType = errors.New("not a valid IntegrationType")

// String implements the Stringer interface.
func (x IntegrationType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x IntegrationType) IsValid() bool {
	_, err := ParseIntegrationType(string(x))
	return err == nil
}

var _IntegrationTypeValue = map[string]IntegrationType{
	"VOICE_MILLIS":    IntegrationTypeVOICEMILLIS,
	"VOICE_VAPI":      IntegrationTypeVOICEVAPI,
	"REDDIT":          IntegrationTypeREDDIT,
	"SLACK_WEBHOOK":   IntegrationTypeSLACKWEBHOOK,
	"REDDIT_DM_LOGIN": IntegrationTypeREDDITDMLOGIN,
}

// ParseIntegrationType attempts to convert a string to a IntegrationType.
func ParseIntegrationType(name string) (IntegrationType, error) {
	if x, ok := _IntegrationTypeValue[name]; ok {
		return x, nil
	}
	return IntegrationType(""), fmt.Errorf("%s is %w", name, ErrInvalidIntegrationType)
}
