// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package models

import (
	"errors"
	"fmt"
)

const (
	// RedditLeadTypeCOMMENT is a RedditLeadType of type COMMENT.
	RedditLeadTypeCOMMENT RedditLeadType = "COMMENT"
	// RedditLeadTypePOST is a RedditLeadType of type POST.
	RedditLeadTypePOST RedditLeadType = "POST"
)

var ErrInvalidRedditLeadType = errors.New("not a valid RedditLeadType")

// String implements the Stringer interface.
func (x RedditLeadType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x RedditLeadType) IsValid() bool {
	_, err := ParseRedditLeadType(string(x))
	return err == nil
}

var _RedditLeadTypeValue = map[string]RedditLeadType{
	"COMMENT": RedditLeadTypeCOMMENT,
	"POST":    RedditLeadTypePOST,
}

// ParseRedditLeadType attempts to convert a string to a RedditLeadType.
func ParseRedditLeadType(name string) (RedditLeadType, error) {
	if x, ok := _RedditLeadTypeValue[name]; ok {
		return x, nil
	}
	return RedditLeadType(""), fmt.Errorf("%s is %w", name, ErrInvalidRedditLeadType)
}
