BEGIN;
DROP TABLE IF EXISTS leads;
DROP INDEX IF EXISTS idx1_leads;
DROP INDEX IF EXISTS idx2_leads;
DROP INDEX IF EXISTS fk1_leads;
DROP INDEX IF EXISTS fk2_leads;
DROP INDEX IF EXISTS fk3_leads;
COMMIT;





