// @generated by protoc-gen-es v2.0.0 with parameter "target=js+dts"
// @generated from file doota/core/v1/core.proto (package doota.core.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Any, Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file doota/core/v1/core.proto.
 */
export declare const file_doota_core_v1_core: GenFile;

/**
 * TzTimestamp is a wrapper around Timestamp that includes a timezone offset
 * for displaying time in a specific timezone. Although timestamps are stored
 * with their extracted timezone offsets in the database (e.g., 2024-10-23 16:19:23 EST
 * is stored as "2024-10-23T16:19:23-05:00" in the DB and not its UTC equivalent of "2024-10-23T21:19:23Z"),
 * we want to ensure they are displayed consistently in the timezone they were extracted from.
 *
 * We cannot use the basic Timestamp object from protobuf because it only
 * represents a UTC timestamp without a timezone offset.
 *
 * Example:
 *     Suppose we have an extracted timestamp of "2024-10-23 16:19:23 EST".
 *     In the database, it will be stored as "2024-10-23T16:19:23-05:00",
 *     preserving the extracted timezone. The TzTimestamp representation would be:
 *
 *     TzTimestamp {
 *         timestamp = 1730233163  // UTC seconds since Unix epoch for 2024-10-23T16:19:23-05:00
 *         offset = -5
 *     }
 *
 * @generated from message doota.core.v1.TzTimestamp
 */
export declare type TzTimestamp = Message<"doota.core.v1.TzTimestamp"> & {
  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 1;
   */
  timestamp?: Timestamp;

  /**
   * @generated from field: int32 offset = 2;
   */
  offset: number;
};

/**
 * Describes the message doota.core.v1.TzTimestamp.
 * Use `create(TzTimestampSchema)` to create a new message.
 */
export declare const TzTimestampSchema: GenMessage<TzTimestamp>;

/**
 * @generated from message doota.core.v1.Identity
 */
export declare type Identity = Message<"doota.core.v1.Identity"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string organization_id = 2;
   */
  organizationId: string;

  /**
   * @generated from field: doota.core.v1.IdentityRole role = 3;
   */
  role: IdentityRole;
};

/**
 * Describes the message doota.core.v1.Identity.
 * Use `create(IdentitySchema)` to create a new message.
 */
export declare const IdentitySchema: GenMessage<Identity>;

/**
 * @generated from message doota.core.v1.PlatformErrorDetails
 */
export declare type PlatformErrorDetails = Message<"doota.core.v1.PlatformErrorDetails"> & {
  /**
   * @generated from field: doota.core.v1.PlatformError error = 1;
   */
  error: PlatformError;

  /**
   * @generated from field: google.protobuf.Any details = 2;
   */
  details?: Any;
};

/**
 * Describes the message doota.core.v1.PlatformErrorDetails.
 * Use `create(PlatformErrorDetailsSchema)` to create a new message.
 */
export declare const PlatformErrorDetailsSchema: GenMessage<PlatformErrorDetails>;

/**
 * @generated from message doota.core.v1.QuoteFormErrorDetails
 */
export declare type QuoteFormErrorDetails = Message<"doota.core.v1.QuoteFormErrorDetails"> & {
  /**
   * @generated from field: repeated doota.core.v1.QuoteFormErrorDetail details = 1;
   */
  details: QuoteFormErrorDetail[];
};

/**
 * Describes the message doota.core.v1.QuoteFormErrorDetails.
 * Use `create(QuoteFormErrorDetailsSchema)` to create a new message.
 */
export declare const QuoteFormErrorDetailsSchema: GenMessage<QuoteFormErrorDetails>;

/**
 * @generated from message doota.core.v1.QuoteFormErrorDetail
 */
export declare type QuoteFormErrorDetail = Message<"doota.core.v1.QuoteFormErrorDetail"> & {
  /**
   * @generated from field: string path = 1;
   */
  path: string;

  /**
   * @generated from field: doota.core.v1.QuoteFormErrorDetail.QuoteFormErrorDetailMessage detail = 2;
   */
  detail: QuoteFormErrorDetail_QuoteFormErrorDetailMessage;
};

/**
 * Describes the message doota.core.v1.QuoteFormErrorDetail.
 * Use `create(QuoteFormErrorDetailSchema)` to create a new message.
 */
export declare const QuoteFormErrorDetailSchema: GenMessage<QuoteFormErrorDetail>;

/**
 * @generated from enum doota.core.v1.QuoteFormErrorDetail.QuoteFormErrorDetailMessage
 */
export enum QuoteFormErrorDetail_QuoteFormErrorDetailMessage {
  /**
   * @generated from enum value: QUOTE_FORM_ERROR_DETAIL_MESSAGE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: QUOTE_FORM_ERROR_DETAIL_MESSAGE_INVALID_GEO = 1;
   */
  INVALID_GEO = 1,
}

/**
 * Describes the enum doota.core.v1.QuoteFormErrorDetail.QuoteFormErrorDetailMessage.
 */
export declare const QuoteFormErrorDetail_QuoteFormErrorDetailMessageSchema: GenEnum<QuoteFormErrorDetail_QuoteFormErrorDetailMessage>;

/**
 * @generated from message doota.core.v1.PricingOptionErrorDetail
 */
export declare type PricingOptionErrorDetail = Message<"doota.core.v1.PricingOptionErrorDetail"> & {
  /**
   * @generated from field: int64 status_code = 1;
   */
  statusCode: bigint;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * @generated from field: string transaction_id = 3;
   */
  transactionId: string;

  /**
   * @generated from field: doota.core.v1.PricingOptionErrorDetail.PricingOptionErrorDetailMessage detail = 4;
   */
  detail: PricingOptionErrorDetail_PricingOptionErrorDetailMessage;
};

/**
 * Describes the message doota.core.v1.PricingOptionErrorDetail.
 * Use `create(PricingOptionErrorDetailSchema)` to create a new message.
 */
export declare const PricingOptionErrorDetailSchema: GenMessage<PricingOptionErrorDetail>;

/**
 * @generated from enum doota.core.v1.PricingOptionErrorDetail.PricingOptionErrorDetailMessage
 */
export enum PricingOptionErrorDetail_PricingOptionErrorDetailMessage {
  /**
   * @generated from enum value: PRICING_OPTION_ERROR_DETAIL_MESSAGE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: PRICING_OPTION_ERROR_DETAIL_MESSAGE_INVALID_ORIGIN = 1;
   */
  INVALID_ORIGIN = 1,

  /**
   * @generated from enum value: PRICING_OPTION_ERROR_DETAIL_MESSAGE_INVALID_DESTINATION = 2;
   */
  INVALID_DESTINATION = 2,
}

/**
 * Describes the enum doota.core.v1.PricingOptionErrorDetail.PricingOptionErrorDetailMessage.
 */
export declare const PricingOptionErrorDetail_PricingOptionErrorDetailMessageSchema: GenEnum<PricingOptionErrorDetail_PricingOptionErrorDetailMessage>;

/**
 * @generated from enum doota.core.v1.PlatformError
 */
export enum PlatformError {
  /**
   * @generated from enum value: PLATFORM_ERROR_UNSPECIFIED = 0;
   */
  PLATFORM_ERROR_UNSPECIFIED = 0,

  /**
   * @generated from enum value: PLATFORM_ERROR_MESSAGE_ALREADY_EXISTS = 1;
   */
  PLATFORM_ERROR_MESSAGE_ALREADY_EXISTS = 1,

  /**
   * @generated from enum value: PLATFORM_ERROR_INVALID_QUOTE = 2;
   */
  PLATFORM_ERROR_INVALID_QUOTE = 2,

  /**
   * @generated from enum value: PLATFORM_UNAUTHORIZED_ACCESS = 3;
   */
  PLATFORM_UNAUTHORIZED_ACCESS = 3,

  /**
   * @generated from enum value: PLATFORM_ERROR_PRICING_OPTION_INVALID_ARG = 4;
   */
  PLATFORM_ERROR_PRICING_OPTION_INVALID_ARG = 4,
}

/**
 * Describes the enum doota.core.v1.PlatformError.
 */
export declare const PlatformErrorSchema: GenEnum<PlatformError>;

/**
 * @generated from enum doota.core.v1.IdentityRole
 */
export enum IdentityRole {
  /**
   * @generated from enum value: IDENTITY_ROLE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: IDENTITY_ROLE_USER = 1;
   */
  USER = 1,

  /**
   * @generated from enum value: IDENTITY_ROLE_ADMIN = 2;
   */
  ADMIN = 2,

  /**
   * @generated from enum value: IDENTITY_ROLE_PLATFORM_ADMIN = 3;
   */
  PLATFORM_ADMIN = 3,
}

/**
 * Describes the enum doota.core.v1.IdentityRole.
 */
export declare const IdentityRoleSchema: GenEnum<IdentityRole>;

/**
 * @generated from enum doota.core.v1.Currency
 */
export enum Currency {
  /**
   * @generated from enum value: CURRENCY_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: CURRENCY_USD = 1;
   */
  USD = 1,

  /**
   * @generated from enum value: CURRENCY_AED = 2;
   */
  AED = 2,

  /**
   * @generated from enum value: CURRENCY_AFN = 3;
   */
  AFN = 3,

  /**
   * @generated from enum value: CURRENCY_ALL = 4;
   */
  ALL = 4,

  /**
   * @generated from enum value: CURRENCY_AMD = 5;
   */
  AMD = 5,

  /**
   * @generated from enum value: CURRENCY_ANG = 6;
   */
  ANG = 6,

  /**
   * @generated from enum value: CURRENCY_AOA = 7;
   */
  AOA = 7,

  /**
   * @generated from enum value: CURRENCY_ARS = 8;
   */
  ARS = 8,

  /**
   * @generated from enum value: CURRENCY_AUD = 9;
   */
  AUD = 9,

  /**
   * @generated from enum value: CURRENCY_AWG = 10;
   */
  AWG = 10,

  /**
   * @generated from enum value: CURRENCY_AZN = 11;
   */
  AZN = 11,

  /**
   * @generated from enum value: CURRENCY_BAM = 12;
   */
  BAM = 12,

  /**
   * @generated from enum value: CURRENCY_BBD = 13;
   */
  BBD = 13,

  /**
   * @generated from enum value: CURRENCY_BDT = 14;
   */
  BDT = 14,

  /**
   * @generated from enum value: CURRENCY_BGN = 15;
   */
  BGN = 15,

  /**
   * @generated from enum value: CURRENCY_BIF = 16;
   */
  BIF = 16,

  /**
   * @generated from enum value: CURRENCY_BMD = 17;
   */
  BMD = 17,

  /**
   * @generated from enum value: CURRENCY_BND = 18;
   */
  BND = 18,

  /**
   * @generated from enum value: CURRENCY_BOB = 19;
   */
  BOB = 19,

  /**
   * @generated from enum value: CURRENCY_BRL = 20;
   */
  BRL = 20,

  /**
   * @generated from enum value: CURRENCY_BSD = 21;
   */
  BSD = 21,

  /**
   * @generated from enum value: CURRENCY_BWP = 22;
   */
  BWP = 22,

  /**
   * @generated from enum value: CURRENCY_BYN = 23;
   */
  BYN = 23,

  /**
   * @generated from enum value: CURRENCY_BZD = 24;
   */
  BZD = 24,

  /**
   * @generated from enum value: CURRENCY_CAD = 25;
   */
  CAD = 25,

  /**
   * @generated from enum value: CURRENCY_CDF = 26;
   */
  CDF = 26,

  /**
   * @generated from enum value: CURRENCY_CHF = 27;
   */
  CHF = 27,

  /**
   * @generated from enum value: CURRENCY_CLP = 28;
   */
  CLP = 28,

  /**
   * @generated from enum value: CURRENCY_CNY = 29;
   */
  CNY = 29,

  /**
   * @generated from enum value: CURRENCY_COP = 30;
   */
  COP = 30,

  /**
   * @generated from enum value: CURRENCY_CRC = 31;
   */
  CRC = 31,

  /**
   * @generated from enum value: CURRENCY_CVE = 32;
   */
  CVE = 32,

  /**
   * @generated from enum value: CURRENCY_CZK = 33;
   */
  CZK = 33,

  /**
   * @generated from enum value: CURRENCY_DJF = 34;
   */
  DJF = 34,

  /**
   * @generated from enum value: CURRENCY_DKK = 35;
   */
  DKK = 35,

  /**
   * @generated from enum value: CURRENCY_DOP = 36;
   */
  DOP = 36,

  /**
   * @generated from enum value: CURRENCY_DZD = 37;
   */
  DZD = 37,

  /**
   * @generated from enum value: CURRENCY_EGP = 38;
   */
  EGP = 38,

  /**
   * @generated from enum value: CURRENCY_ETB = 39;
   */
  ETB = 39,

  /**
   * @generated from enum value: CURRENCY_EUR = 40;
   */
  EUR = 40,

  /**
   * @generated from enum value: CURRENCY_FJD = 41;
   */
  FJD = 41,

  /**
   * @generated from enum value: CURRENCY_FKP = 42;
   */
  FKP = 42,

  /**
   * @generated from enum value: CURRENCY_GBP = 43;
   */
  GBP = 43,

  /**
   * @generated from enum value: CURRENCY_GEL = 44;
   */
  GEL = 44,

  /**
   * @generated from enum value: CURRENCY_GIP = 45;
   */
  GIP = 45,

  /**
   * @generated from enum value: CURRENCY_GMD = 46;
   */
  GMD = 46,

  /**
   * @generated from enum value: CURRENCY_GNF = 47;
   */
  GNF = 47,

  /**
   * @generated from enum value: CURRENCY_GTQ = 48;
   */
  GTQ = 48,

  /**
   * @generated from enum value: CURRENCY_GYD = 49;
   */
  GYD = 49,

  /**
   * @generated from enum value: CURRENCY_HKD = 50;
   */
  HKD = 50,

  /**
   * @generated from enum value: CURRENCY_HNL = 51;
   */
  HNL = 51,

  /**
   * @generated from enum value: CURRENCY_HTG = 52;
   */
  HTG = 52,

  /**
   * @generated from enum value: CURRENCY_HUF = 53;
   */
  HUF = 53,

  /**
   * @generated from enum value: CURRENCY_IDR = 54;
   */
  IDR = 54,

  /**
   * @generated from enum value: CURRENCY_ILS = 55;
   */
  ILS = 55,

  /**
   * @generated from enum value: CURRENCY_INR = 56;
   */
  INR = 56,

  /**
   * @generated from enum value: CURRENCY_ISK = 57;
   */
  ISK = 57,

  /**
   * @generated from enum value: CURRENCY_JMD = 58;
   */
  JMD = 58,

  /**
   * @generated from enum value: CURRENCY_JPY = 59;
   */
  JPY = 59,

  /**
   * @generated from enum value: CURRENCY_KES = 60;
   */
  KES = 60,

  /**
   * @generated from enum value: CURRENCY_KGS = 61;
   */
  KGS = 61,

  /**
   * @generated from enum value: CURRENCY_KHR = 62;
   */
  KHR = 62,

  /**
   * @generated from enum value: CURRENCY_KMF = 63;
   */
  KMF = 63,

  /**
   * @generated from enum value: CURRENCY_KRW = 64;
   */
  KRW = 64,

  /**
   * @generated from enum value: CURRENCY_KYD = 65;
   */
  KYD = 65,

  /**
   * @generated from enum value: CURRENCY_KZT = 66;
   */
  KZT = 66,

  /**
   * @generated from enum value: CURRENCY_LAK = 67;
   */
  LAK = 67,

  /**
   * @generated from enum value: CURRENCY_LBP = 68;
   */
  LBP = 68,

  /**
   * @generated from enum value: CURRENCY_LKR = 69;
   */
  LKR = 69,

  /**
   * @generated from enum value: CURRENCY_LRD = 70;
   */
  LRD = 70,

  /**
   * @generated from enum value: CURRENCY_LSL = 71;
   */
  LSL = 71,

  /**
   * @generated from enum value: CURRENCY_MAD = 72;
   */
  MAD = 72,

  /**
   * @generated from enum value: CURRENCY_MDL = 73;
   */
  MDL = 73,

  /**
   * @generated from enum value: CURRENCY_MGA = 74;
   */
  MGA = 74,

  /**
   * @generated from enum value: CURRENCY_MKD = 75;
   */
  MKD = 75,

  /**
   * @generated from enum value: CURRENCY_MMK = 76;
   */
  MMK = 76,

  /**
   * @generated from enum value: CURRENCY_MNT = 77;
   */
  MNT = 77,

  /**
   * @generated from enum value: CURRENCY_MOP = 78;
   */
  MOP = 78,

  /**
   * @generated from enum value: CURRENCY_MUR = 79;
   */
  MUR = 79,

  /**
   * @generated from enum value: CURRENCY_MVR = 80;
   */
  MVR = 80,

  /**
   * @generated from enum value: CURRENCY_MWK = 81;
   */
  MWK = 81,

  /**
   * @generated from enum value: CURRENCY_MXN = 82;
   */
  MXN = 82,

  /**
   * @generated from enum value: CURRENCY_MYR = 83;
   */
  MYR = 83,

  /**
   * @generated from enum value: CURRENCY_MZN = 84;
   */
  MZN = 84,

  /**
   * @generated from enum value: CURRENCY_NAD = 85;
   */
  NAD = 85,

  /**
   * @generated from enum value: CURRENCY_NGN = 86;
   */
  NGN = 86,

  /**
   * @generated from enum value: CURRENCY_NIO = 87;
   */
  NIO = 87,

  /**
   * @generated from enum value: CURRENCY_NOK = 88;
   */
  NOK = 88,

  /**
   * @generated from enum value: CURRENCY_NPR = 89;
   */
  NPR = 89,

  /**
   * @generated from enum value: CURRENCY_NZD = 90;
   */
  NZD = 90,

  /**
   * @generated from enum value: CURRENCY_PAB = 91;
   */
  PAB = 91,

  /**
   * @generated from enum value: CURRENCY_PEN = 92;
   */
  PEN = 92,

  /**
   * @generated from enum value: CURRENCY_PGK = 93;
   */
  PGK = 93,

  /**
   * @generated from enum value: CURRENCY_PHP = 94;
   */
  PHP = 94,

  /**
   * @generated from enum value: CURRENCY_PKR = 95;
   */
  PKR = 95,

  /**
   * @generated from enum value: CURRENCY_PLN = 96;
   */
  PLN = 96,

  /**
   * @generated from enum value: CURRENCY_PYG = 97;
   */
  PYG = 97,

  /**
   * @generated from enum value: CURRENCY_QAR = 98;
   */
  QAR = 98,

  /**
   * @generated from enum value: CURRENCY_RON = 99;
   */
  RON = 99,

  /**
   * @generated from enum value: CURRENCY_RSD = 100;
   */
  RSD = 100,

  /**
   * @generated from enum value: CURRENCY_RUB = 101;
   */
  RUB = 101,

  /**
   * @generated from enum value: CURRENCY_RWF = 102;
   */
  RWF = 102,

  /**
   * @generated from enum value: CURRENCY_SAR = 103;
   */
  SAR = 103,

  /**
   * @generated from enum value: CURRENCY_SBD = 104;
   */
  SBD = 104,

  /**
   * @generated from enum value: CURRENCY_SCR = 105;
   */
  SCR = 105,

  /**
   * @generated from enum value: CURRENCY_SEK = 106;
   */
  SEK = 106,

  /**
   * @generated from enum value: CURRENCY_SGD = 107;
   */
  SGD = 107,

  /**
   * @generated from enum value: CURRENCY_SHP = 108;
   */
  SHP = 108,

  /**
   * @generated from enum value: CURRENCY_SLE = 109;
   */
  SLE = 109,

  /**
   * @generated from enum value: CURRENCY_SOS = 110;
   */
  SOS = 110,

  /**
   * @generated from enum value: CURRENCY_SRD = 111;
   */
  SRD = 111,

  /**
   * @generated from enum value: CURRENCY_STD = 112;
   */
  STD = 112,

  /**
   * @generated from enum value: CURRENCY_SZL = 113;
   */
  SZL = 113,

  /**
   * @generated from enum value: CURRENCY_THB = 114;
   */
  THB = 114,

  /**
   * @generated from enum value: CURRENCY_TJS = 115;
   */
  TJS = 115,

  /**
   * @generated from enum value: CURRENCY_TOP = 116;
   */
  TOP = 116,

  /**
   * @generated from enum value: CURRENCY_TRY = 117;
   */
  TRY = 117,

  /**
   * @generated from enum value: CURRENCY_TTD = 118;
   */
  TTD = 118,

  /**
   * @generated from enum value: CURRENCY_TWD = 119;
   */
  TWD = 119,

  /**
   * @generated from enum value: CURRENCY_TZS = 120;
   */
  TZS = 120,

  /**
   * @generated from enum value: CURRENCY_UAH = 121;
   */
  UAH = 121,

  /**
   * @generated from enum value: CURRENCY_UGX = 122;
   */
  UGX = 122,

  /**
   * @generated from enum value: CURRENCY_UYU = 123;
   */
  UYU = 123,

  /**
   * @generated from enum value: CURRENCY_UZS = 124;
   */
  UZS = 124,

  /**
   * @generated from enum value: CURRENCY_VND = 125;
   */
  VND = 125,

  /**
   * @generated from enum value: CURRENCY_VUV = 126;
   */
  VUV = 126,

  /**
   * @generated from enum value: CURRENCY_WST = 127;
   */
  WST = 127,

  /**
   * @generated from enum value: CURRENCY_XAF = 128;
   */
  XAF = 128,

  /**
   * @generated from enum value: CURRENCY_XCD = 129;
   */
  XCD = 129,

  /**
   * @generated from enum value: CURRENCY_XOF = 130;
   */
  XOF = 130,

  /**
   * @generated from enum value: CURRENCY_XPF = 131;
   */
  XPF = 131,

  /**
   * @generated from enum value: CURRENCY_YER = 132;
   */
  YER = 132,

  /**
   * @generated from enum value: CURRENCY_ZAR = 133;
   */
  ZAR = 133,

  /**
   * @generated from enum value: CURRENCY_ZMW = 134;
   */
  ZMW = 134,
}

/**
 * Describes the enum doota.core.v1.Currency.
 */
export declare const CurrencySchema: GenEnum<Currency>;

