// @generated by protoc-gen-es v2.0.0 with parameter "target=js+dts"
// @generated from file doota/core/v1/insight.proto (package doota.core.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_google_protobuf_any, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file doota/core/v1/insight.proto.
 */
export const file_doota_core_v1_insight = /*@__PURE__*/
  fileDesc("Chtkb290YS9jb3JlL3YxL2luc2lnaHQucHJvdG8SDWRvb3RhLmNvcmUudjEijAIKC1Bvc3RJbnNpZ2h0EgoKAmlkGAEgASgJEhIKCnByb2plY3RfaWQYAiABKAkSDgoGc291cmNlGAMgASgJEg8KB3Bvc3RfaWQYBCABKAkSDQoFdG9waWMYBSABKAkSEgoKaGlnaGxpZ2h0cxgGIAEoCRIXCg9yZWxldmFuY3lfc2NvcmUYByABKAESEQoJc2VudGltZW50GAggASgJEhIKCnBvc3RfdGl0bGUYCSABKAkSHAoUaGlnaGxpZ2h0ZWRfY29tbWVudHMYCiADKAkSCwoDY290GAsgASgJEi4KCmNyZWF0ZWRfYXQYDCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wQjNaMWdpdGh1Yi5jb20vc2hhbmszMTgvZG9vdGEvcGIvZG9vdGEvY29yZS92MTtwYmNvcmViBnByb3RvMw", [file_google_protobuf_timestamp, file_google_protobuf_any]);

/**
 * Describes the message doota.core.v1.PostInsight.
 * Use `create(PostInsightSchema)` to create a new message.
 */
export const PostInsightSchema = /*@__PURE__*/
  messageDesc(file_doota_core_v1_insight, 0);

