// @generated by protoc-gen-es v2.0.0 with parameter "target=js+dts"
// @generated from file doota/core/v1/insight.proto (package doota.core.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file doota/core/v1/insight.proto.
 */
export declare const file_doota_core_v1_insight: GenFile;

/**
 * @generated from message doota.core.v1.PostInsight
 */
export declare type PostInsight = Message<"doota.core.v1.PostInsight"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string project_id = 2;
   */
  projectId: string;

  /**
   * @generated from field: string source = 3;
   */
  source: string;

  /**
   * @generated from field: string post_id = 4;
   */
  postId: string;

  /**
   * @generated from field: string topic = 5;
   */
  topic: string;

  /**
   * @generated from field: string highlights = 6;
   */
  highlights: string;

  /**
   * @generated from field: double relevancy_score = 7;
   */
  relevancyScore: number;

  /**
   * @generated from field: string sentiment = 8;
   */
  sentiment: string;

  /**
   * @generated from field: string post_title = 9;
   */
  postTitle: string;

  /**
   * @generated from field: repeated string highlighted_comments = 10;
   */
  highlightedComments: string[];

  /**
   * @generated from field: string cot = 11;
   */
  cot: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 12;
   */
  createdAt?: Timestamp;
};

/**
 * Describes the message doota.core.v1.PostInsight.
 * Use `create(PostInsightSchema)` to create a new message.
 */
export declare const PostInsightSchema: GenMessage<PostInsight>;

