// @generated by protoc-gen-es v2.0.0 with parameter "target=js+dts"
// @generated from file doota/core/v1/post.proto (package doota.core.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv1";
import { file_google_protobuf_any, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file doota/core/v1/post.proto.
 */
export const file_doota_core_v1_post = /*@__PURE__*/
  fileDesc("Chhkb290YS9jb3JlL3YxL3Bvc3QucHJvdG8SDWRvb3RhLmNvcmUudjEioQIKBFBvc3QSCgoCaWQYASABKAkSEgoKcHJvamVjdF9pZBgCIAEoCRIOCgZzb3VyY2UYAyABKAkSDQoFdG9waWMYBCABKAkSEwoLZGVzY3JpcHRpb24YBSABKAkSDgoGc3RhdHVzGAYgASgJEg4KBnJlYXNvbhgHIAEoCRIuCgpjcmVhdGVkX2F0GAggASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBI1CgxzY2hlZHVsZWRfYXQYCSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wSACIAQESLQoIbWV0YWRhdGEYCyABKAsyGy5kb290YS5jb3JlLnYxLlBvc3RNZXRhZGF0YUIPCg1fc2NoZWR1bGVkX2F0IqEBCgxQb3N0U2V0dGluZ3MSDQoFdG9waWMYASABKAkSDwoHY29udGV4dBgCIAEoCRIMCgRnb2FsGAMgASgJEgwKBHRvbmUYBCABKAkSGQoMcmVmZXJlbmNlX2lkGAUgASgJSACIAQESDwoCaWQYBiABKAlIAYgBARIRCglzb3VyY2VfaWQYByABKAlCDwoNX3JlZmVyZW5jZV9pZEIFCgNfaWQidgoMUG9zdE1ldGFkYXRhEi0KCHNldHRpbmdzGAEgASgLMhsuZG9vdGEuY29yZS52MS5Qb3N0U2V0dGluZ3MSNwoHaGlzdG9yeRgCIAMoCzImLmRvb3RhLmNvcmUudjEuUG9zdFJlZ2VuZXJhdGlvbkhpc3RvcnkicQoXUG9zdFJlZ2VuZXJhdGlvbkhpc3RvcnkSMgoNcG9zdF9zZXR0aW5ncxgBIAEoCzIbLmRvb3RhLmNvcmUudjEuUG9zdFNldHRpbmdzEg0KBXRpdGxlGAIgASgJEhMKC2Rlc2NyaXB0aW9uGAMgASgJIkcKDUF1Z21lbnRlZFBvc3QSIQoEcG9zdBgBIAEoCzITLmRvb3RhLmNvcmUudjEuUG9zdBITCgtzb3VyY2VfbmFtZRgCIAEoCSJSChNTY2hlZHVsZVBvc3RSZXF1ZXN0EgoKAmlkGAEgASgJEi8KC3NjaGVkdWxlX2F0GAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCqnAQoKUG9zdFN0YXR1cxIbChdQT1NUX1NUQVRVU19VTlNQRUNJRklFRBAAEhcKE1BPU1RfU1RBVFVTX0NSRUFURUQQARIaChZQT1NUX1NUQVRVU19QUk9DRVNTSU5HEAISFAoQUE9TVF9TVEFUVVNfU0VOVBADEhYKElBPU1RfU1RBVFVTX0ZBSUxFRBAEEhkKFVBPU1RfU1RBVFVTX1NDSEVEVUxFRBAFQjNaMWdpdGh1Yi5jb20vc2hhbmszMTgvZG9vdGEvcGIvZG9vdGEvY29yZS92MTtwYmNvcmViBnByb3RvMw", [file_google_protobuf_timestamp, file_google_protobuf_any]);

/**
 * Describes the message doota.core.v1.Post.
 * Use `create(PostSchema)` to create a new message.
 */
export const PostSchema = /*@__PURE__*/
  messageDesc(file_doota_core_v1_post, 0);

/**
 * Describes the message doota.core.v1.PostSettings.
 * Use `create(PostSettingsSchema)` to create a new message.
 */
export const PostSettingsSchema = /*@__PURE__*/
  messageDesc(file_doota_core_v1_post, 1);

/**
 * Describes the message doota.core.v1.PostMetadata.
 * Use `create(PostMetadataSchema)` to create a new message.
 */
export const PostMetadataSchema = /*@__PURE__*/
  messageDesc(file_doota_core_v1_post, 2);

/**
 * Describes the message doota.core.v1.PostRegenerationHistory.
 * Use `create(PostRegenerationHistorySchema)` to create a new message.
 */
export const PostRegenerationHistorySchema = /*@__PURE__*/
  messageDesc(file_doota_core_v1_post, 3);

/**
 * Describes the message doota.core.v1.AugmentedPost.
 * Use `create(AugmentedPostSchema)` to create a new message.
 */
export const AugmentedPostSchema = /*@__PURE__*/
  messageDesc(file_doota_core_v1_post, 4);

/**
 * Describes the message doota.core.v1.SchedulePostRequest.
 * Use `create(SchedulePostRequestSchema)` to create a new message.
 */
export const SchedulePostRequestSchema = /*@__PURE__*/
  messageDesc(file_doota_core_v1_post, 5);

/**
 * Describes the enum doota.core.v1.PostStatus.
 */
export const PostStatusSchema = /*@__PURE__*/
  enumDesc(file_doota_core_v1_post, 0);

/**
 * @generated from enum doota.core.v1.PostStatus
 */
export const PostStatus = /*@__PURE__*/
  tsEnum(PostStatusSchema);

