// @generated by protoc-gen-es v2.0.0 with parameter "target=js+dts"
// @generated from file doota/core/v1/post.proto (package doota.core.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file doota/core/v1/post.proto.
 */
export declare const file_doota_core_v1_post: GenFile;

/**
 * @generated from message doota.core.v1.Post
 */
export declare type Post = Message<"doota.core.v1.Post"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string project_id = 2;
   */
  projectId: string;

  /**
   * @generated from field: string source = 3;
   */
  source: string;

  /**
   * @generated from field: string topic = 4;
   */
  topic: string;

  /**
   * @generated from field: string description = 5;
   */
  description: string;

  /**
   * @generated from field: string status = 6;
   */
  status: string;

  /**
   * @generated from field: string reason = 7;
   */
  reason: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 8;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: optional google.protobuf.Timestamp scheduled_at = 9;
   */
  scheduledAt?: Timestamp;

  /**
   * @generated from field: doota.core.v1.PostMetadata metadata = 11;
   */
  metadata?: PostMetadata;
};

/**
 * Describes the message doota.core.v1.Post.
 * Use `create(PostSchema)` to create a new message.
 */
export declare const PostSchema: GenMessage<Post>;

/**
 * @generated from message doota.core.v1.PostSettings
 */
export declare type PostSettings = Message<"doota.core.v1.PostSettings"> & {
  /**
   * @generated from field: string topic = 1;
   */
  topic: string;

  /**
   * @generated from field: string context = 2;
   */
  context: string;

  /**
   * @generated from field: string goal = 3;
   */
  goal: string;

  /**
   * @generated from field: string tone = 4;
   */
  tone: string;

  /**
   * @generated from field: optional string reference_id = 5;
   */
  referenceId?: string;

  /**
   * unique identifier for the post settings
   *
   * @generated from field: optional string id = 6;
   */
  id?: string;

  /**
   * @generated from field: string source_id = 7;
   */
  sourceId: string;
};

/**
 * Describes the message doota.core.v1.PostSettings.
 * Use `create(PostSettingsSchema)` to create a new message.
 */
export declare const PostSettingsSchema: GenMessage<PostSettings>;

/**
 * @generated from message doota.core.v1.PostMetadata
 */
export declare type PostMetadata = Message<"doota.core.v1.PostMetadata"> & {
  /**
   * @generated from field: doota.core.v1.PostSettings settings = 1;
   */
  settings?: PostSettings;

  /**
   * @generated from field: repeated doota.core.v1.PostRegenerationHistory history = 2;
   */
  history: PostRegenerationHistory[];
};

/**
 * Describes the message doota.core.v1.PostMetadata.
 * Use `create(PostMetadataSchema)` to create a new message.
 */
export declare const PostMetadataSchema: GenMessage<PostMetadata>;

/**
 * @generated from message doota.core.v1.PostRegenerationHistory
 */
export declare type PostRegenerationHistory = Message<"doota.core.v1.PostRegenerationHistory"> & {
  /**
   * @generated from field: doota.core.v1.PostSettings post_settings = 1;
   */
  postSettings?: PostSettings;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;
};

/**
 * Describes the message doota.core.v1.PostRegenerationHistory.
 * Use `create(PostRegenerationHistorySchema)` to create a new message.
 */
export declare const PostRegenerationHistorySchema: GenMessage<PostRegenerationHistory>;

/**
 * @generated from message doota.core.v1.AugmentedPost
 */
export declare type AugmentedPost = Message<"doota.core.v1.AugmentedPost"> & {
  /**
   * Base post information
   *
   * @generated from field: doota.core.v1.Post post = 1;
   */
  post?: Post;

  /**
   * Additional field
   *
   * @generated from field: string source_name = 2;
   */
  sourceName: string;
};

/**
 * Describes the message doota.core.v1.AugmentedPost.
 * Use `create(AugmentedPostSchema)` to create a new message.
 */
export declare const AugmentedPostSchema: GenMessage<AugmentedPost>;

/**
 * @generated from message doota.core.v1.SchedulePostRequest
 */
export declare type SchedulePostRequest = Message<"doota.core.v1.SchedulePostRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: google.protobuf.Timestamp schedule_at = 2;
   */
  scheduleAt?: Timestamp;
};

/**
 * Describes the message doota.core.v1.SchedulePostRequest.
 * Use `create(SchedulePostRequestSchema)` to create a new message.
 */
export declare const SchedulePostRequestSchema: GenMessage<SchedulePostRequest>;

/**
 * @generated from enum doota.core.v1.PostStatus
 */
export enum PostStatus {
  /**
   * @generated from enum value: POST_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: POST_STATUS_CREATED = 1;
   */
  CREATED = 1,

  /**
   * @generated from enum value: POST_STATUS_PROCESSING = 2;
   */
  PROCESSING = 2,

  /**
   * @generated from enum value: POST_STATUS_SENT = 3;
   */
  SENT = 3,

  /**
   * @generated from enum value: POST_STATUS_FAILED = 4;
   */
  FAILED = 4,

  /**
   * @generated from enum value: POST_STATUS_SCHEDULED = 5;
   */
  SCHEDULED = 5,
}

/**
 * Describes the enum doota.core.v1.PostStatus.
 */
export declare const PostStatusSchema: GenEnum<PostStatus>;

