// @generated by protoc-gen-es v2.0.0 with parameter "target=js+dts"
// @generated from file doota/core/v1/post.proto (package doota.core.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv1";
import { file_google_protobuf_any, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file doota/core/v1/post.proto.
 */
export const file_doota_core_v1_post = /*@__PURE__*/
  fileDesc("Chhkb290YS9jb3JlL3YxL3Bvc3QucHJvdG8SDWRvb3RhLmNvcmUudjEioQIKBFBvc3QSCgoCaWQYASABKAkSEgoKcHJvamVjdF9pZBgCIAEoCRIOCgZzb3VyY2UYAyABKAkSDQoFdG9waWMYBCABKAkSEwoLZGVzY3JpcHRpb24YBSABKAkSDgoGc3RhdHVzGAYgASgJEg4KBnJlYXNvbhgHIAEoCRIuCgpjcmVhdGVkX2F0GAggASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBI1CgxzY2hlZHVsZWRfYXQYCSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wSACIAQESLQoIbWV0YWRhdGEYCyABKAsyGy5kb290YS5jb3JlLnYxLlBvc3RNZXRhZGF0YUIPCg1fc2NoZWR1bGVkX2F0InYKDFBvc3RTZXR0aW5ncxINCgV0b3BpYxgBIAEoCRIPCgdjb250ZXh0GAIgASgJEgwKBGdvYWwYAyABKAkSDAoEdG9uZRgEIAEoCRIZCgxyZWZlcmVuY2VfaWQYBSABKAlIAIgBAUIPCg1fcmVmZXJlbmNlX2lkInYKDFBvc3RNZXRhZGF0YRItCghzZXR0aW5ncxgBIAEoCzIbLmRvb3RhLmNvcmUudjEuUG9zdFNldHRpbmdzEjcKB2hpc3RvcnkYAiADKAsyJi5kb290YS5jb3JlLnYxLlBvc3RSZWdlbmVyYXRpb25IaXN0b3J5IlsKF1Bvc3RSZWdlbmVyYXRpb25IaXN0b3J5EjIKDXBvc3Rfc2V0dGluZ3MYASABKAsyGy5kb290YS5jb3JlLnYxLlBvc3RTZXR0aW5ncxIMCgR0ZXh0GAIgASgJKqcBCgpQb3N0U3RhdHVzEhsKF1BPU1RfU1RBVFVTX1VOU1BFQ0lGSUVEEAASFwoTUE9TVF9TVEFUVVNfQ1JFQVRFRBABEhoKFlBPU1RfU1RBVFVTX1BST0NFU1NJTkcQAhIUChBQT1NUX1NUQVRVU19TRU5UEAMSFgoSUE9TVF9TVEFUVVNfRkFJTEVEEAQSGQoVUE9TVF9TVEFUVVNfU0NIRURVTEVEEAVCM1oxZ2l0aHViLmNvbS9zaGFuazMxOC9kb290YS9wYi9kb290YS9jb3JlL3YxO3BiY29yZWIGcHJvdG8z", [file_google_protobuf_timestamp, file_google_protobuf_any]);

/**
 * Describes the message doota.core.v1.Post.
 * Use `create(PostSchema)` to create a new message.
 */
export const PostSchema = /*@__PURE__*/
  messageDesc(file_doota_core_v1_post, 0);

/**
 * Describes the message doota.core.v1.PostSettings.
 * Use `create(PostSettingsSchema)` to create a new message.
 */
export const PostSettingsSchema = /*@__PURE__*/
  messageDesc(file_doota_core_v1_post, 1);

/**
 * Describes the message doota.core.v1.PostMetadata.
 * Use `create(PostMetadataSchema)` to create a new message.
 */
export const PostMetadataSchema = /*@__PURE__*/
  messageDesc(file_doota_core_v1_post, 2);

/**
 * Describes the message doota.core.v1.PostRegenerationHistory.
 * Use `create(PostRegenerationHistorySchema)` to create a new message.
 */
export const PostRegenerationHistorySchema = /*@__PURE__*/
  messageDesc(file_doota_core_v1_post, 3);

/**
 * Describes the enum doota.core.v1.PostStatus.
 */
export const PostStatusSchema = /*@__PURE__*/
  enumDesc(file_doota_core_v1_post, 0);

/**
 * @generated from enum doota.core.v1.PostStatus
 */
export const PostStatus = /*@__PURE__*/
  tsEnum(PostStatusSchema);

